### PR TITLE
[BPOSANDJAX-1047] Support Cash Discount FRD V1.01

### PR DESCRIPTION
**Pull request by azvasquez-pax**
Parent: https://github.com/PAXTechnologyInc/BroadPOS-Manager/pull/681

### CODE REVIEW

**Review by DhruboPaulPax — COMMENTED** [review]
Confirm Cash Payment INPUT EXTRAS:
PARAM_PACKAGE, PARAM_TRANS_TYPE, PARAM_TRANS_MODE
PARAM_TOTAL_AMOUNT, PARAM_CURRENCY
PARAM_MESSAGE (optional), PARAM_OPTIONS (optional)

**Review by DhruboPaulPax — CHANGES_REQUESTED** [review]
Confirm Cash Payment INPUT EXTRAS:
PARAM_PACKAGE, PARAM_TRANS_TYPE, PARAM_TRANS_MODE
PARAM_TOTAL_AMOUNT, PARAM_CURRENCY
PARAM_MESSAGE (optional), PARAM_OPTIONS (optional)

Total Amount and Currency are mandatory, need to be added in the comment.
They have also been used in DefaultUI activity.

**Review by DhruboPaulPax — CHANGES_REQUESTED** [review]
CONFIRM_CASH_PAYMENT should be in ConfirmationEntry Category.

**Comment by azvasquez-pax** [comment]
We will prefer https://github.com/PAXTechnologyInc/POSLink-UI/pull/104

**Pull request closed without merging**
